AWSTemplateFormatVersion: 2010-09-09

Description: |
  This is the webserver for Kittens Carusel project. 
  Creating an EC2 instance with a user data that installs 
  Apache web server.

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of the key pair you want to use for this web server.
    
  MySecurityGroup:
    Description: My security group name for web server.
    Type: AWS::EC2::SecurityGroup::GroupName

Resources:
  KittensCaruselWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07e1aeb90edb268a3
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      SecurityGroups: 
        - !Ref MySecurityGroup 
      Tags:
        - Key: Name
          Value: joshua-kittens-lesson
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          dnf update -y
          dnf install git httpd -y
          cd /home/ec2-user
          git clone https://github.com/ikjosh/Project-101-kittens-carousel-static-website-ec2-CF.git app
          cp /home/ec2-user/app/static-web/* /var/www/html
          systemctl start httpd
          systemctl enable httpd 

Outputs:
  MyPublicIPAddress:
    Description: The public IP of my instance.
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt KittensCaruselWebServer.PublicIp
    